[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_token_vesting_minimal = "V1st1ng111111111111111111111111111111111112"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/**/*.ts"
